# Welcome to Jekyll!

# Website settings
title: Clément Gaultier - Clément Gaultier
description: Clément Gaultier, Research Fellow - University of Cambridge. 
keywords: Clément Gaultier Auditory Sound Acoustics DSP Signal Processing Audio Declipping Denoising Hearing Aid Speech Enhancement Clement Audio University Cambridge
baseurl: 
url: https://gaultier.io
#url: http://127.0.0.1:4000
img_path:
cvButton: Download my detailed CV
cvLink: /static/assets/pdf/CV_academia_ClementGAULTIER.pdf

# author
author:
  name: Clément Gaultier
  first_name: Clément
  last_name: Gaultier
  cv: https://gaultier.io/static/assets/pdf/CV_academia_ClementGAULTIER.pdf #https://cv.gaultier.io/CV_en_ClementGAULTIER.pdf
  email: clement@gaultier.io
  facebook_username: # removed in the template
  github_username: # removed in the template
  linkedin_id: clement-gaultier
  #viadeo_address: http://www.viadeo.com/p/002e58nukfal0ds
  twitter_username:
  scholar_address: https://scholar.google.com/citations?user=pP4U2sMAAAAJ&hl=en
  avatar: /static/assets/img/landing/Clement.png
  skill_icon1:
    - name: fa-headphones
    - name: icon-shell
  skill_icon2:
    - name: fa-assistive-listening-systems
    - name: fa-microphone
  desc: "I work as a Research Fellow at the University of Cambridge, studying with a multidisciplinary approach, new speech enhancement strategies able to cope with noise and reverberation for cochlear implants users. My research topics mainly comprise solving acoustic and audio signal processing inverse problems. During my PhD I had been working on declipping and denoising using analysis/synthesis sparse priors. I also worked on binaural sound source localization with massive regressions machine learning techniques. Additionally, I am really interested in auditory related topics such as augmented hearing, or hearing protection."

# comment
# disqus:
#   name:

# analytics
## google analytics
ga:
 id: UA-113020414-1

#go:
#  id:

## donation
donation: off

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
- jekyll-email-protect
